travis:
  secure:
    BINSTAR_TOKEN: ssP7JG9oLQ4bOqaymHl09othtJmkFedjSfoPw/BPRSiWBNQ+kNP5fjxaUVNP/6bjejcRDZtJCx1EeeNqN0c/uG40fpPrJaOnAXCrlyzqm5N+AP7ne1hf7hMXkoJ10NRV2jTGleySXVgLzXDe/oT4rsRmH2j/Pvt99OhJjo+eCMQMuNlhCK2w/V6An0VZ0Kmzo//Xdb4CJG2ySmoigA3rW2QT6s+MwDt6JV0k8wcWOAS51cKJYyRyc+5Y+KadLbhECwlzRR/qGLxlrO9/2aZ6P/Lr8+GRHmJifls2F3rzBUFeu0d7zs54BzeyH4yRaFas5IvlOcnRVfSkdKUWmGm6DhJ2xFtihCKCWeADYGM9viTtEDfTo1IDTAQiJ2C8gFi5GW8ziuK9Bpp1ICFaRaYT8enn1Dz5GwNB+aEgko2NlrCh8yGiUShFwCDVoMqL9BYTfT4xIoDemKtCZ3v2j8fESXg78cJ7X8VHgVs0N/74yYYvrjFvYKXpxM2WoxkvYMb+8/3d51qcf4UnikEmLQCV+ev1wrFNiwAO5Q1km9wW4Mj1rsJi2ki7+068YIBuLR/gghKEA9y7tyW5pNgyiqeeOVPkfcda7dfw9wS95VOn9YuB+h92DcsY/M/un8BlwJ8I8UZ1MvfjIBr29nhQZySwnX3EZCvZxYKK0YYDad48f8M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
